### ISSUE TITLE
Add Pclub summer of code

### ISSUE THREAD

**Issue by tharun143** [deepanshu1422/List-Of-Open-Source-Internships-Programs#1]
Programming Club UIET or PCIub for short is a student-driven society that aims at educating students about various domains of Computer Science, Electronics, and Technology.

[Pclub]( https://www.pclubsummerofcode.in/)

**Comment by deepanshu1422** [comment]
@tharun143  make sure to star and share this repo with your friends 
https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs
