### ISSUE TITLE
Fix git history

### ISSUE THREAD

**Issue by palash25** [deepanshu1422/List-Of-Open-Source-Internships-Programs#11]
This repo doesn't list commits from the original contributors of https://github.com/tapaswenipathak/Open-Source-Programs
I am assuming that you copy-pasted the contents of the original repo and then intialized this as a git repo and committed them under your name and have been accepting contributions since then. I am not accusing anyone just wanted to let you know that it would be fair to the past contributors if their commits were included and the history was fixed (the correct way to go about it would have been to fork the original repo, anyway too late for that)

How to do it?
- Add the remote of this repo to your clone of the original https://github.com/tapaswenipathak/Open-Source-Programs
- Fetch the master branch from this repo's remote to the clone of original https://github.com/tapaswenipathak/Open-Source-Programs
- checkout to the master of the original https://github.com/tapaswenipathak/Open-Source-Programs
- cherry pick the commits from your branch that you just fetched on top of the original's master
- push the original's master to this remote

**Comment by deepanshu1422** [comment]
Hi Palash, I was new to concepts of git while I was starting to contribute and host on Github. I saw that there was a stale repository of Tapeswini and decided to work upon it, It was none of my intention to plagiarise or not giving the due credits to previous contributors. I have sent you the invite to collaborate on this repository with administrator rights and it would be really helpful if you could do the required changes.

Thanks 👍

**Comment by palash25** [comment]
>  It was none of my intention to plagiarise or not giving the due credits to previous contributors

Hi @deepanshu1422 I know that you weren't looking to plagiarise from the original repo thats cool.

>  I have sent you the invite to collaborate on this repository with administrator rights and it would be really helpful if you could do the required changes.

I am busy these days plus I have an RSI, I am not even typing these comments and dictating them instead so I won't be able to do this for a few months at least. 

I have listed out all the steps and I think you should do it instead as you will get to learn more about git, also its not that hard. :wink:

**Comment by palash25** [comment]
I am accepting the invitation just in case I wish to collaborate in future. thanks for that.

**Comment by deepanshu1422** [comment]
Yeah sure, I'll do that soon. Thanks for the help btw!

**Comment by palash25** [comment]
this issue wasn't resolved so no point in closing it, I request you to reopen it till it is resolved.
