### ISSUE TITLE
New Pull Request Guidelines.

### ISSUE THREAD

**Issue by vybhav72954** [deepanshu1422/List-Of-Open-Source-Internships-Programs#16]
There should be a separate list of guidelines to help the contributors make easy and valid contributions.

# Suggestion - 

- If there is no separate timeline page (i.e. it is available on the home landing page), should the contributor mention the website in the timeline column or not?

Contributors should be encouraged to mention the Month / Week (in a predetermined format) if a separate timeline is not available.

**Comment by deepanshu1422** [comment]
@vybhav72954  Got it, but I'm busy this week...and would really appreciate if you could please sort it out , I'm making you the admin of this repository!😊

**Comment by vybhav72954** [comment]
Sure thing. I will ensure that the Repo is up to date and free of errors.

> @vybhav72954 Got it, but I'm busy this week...and would really appreciate if you could please sort it out, I'm adding you to the collaborators of this repository, kindly accept the invitation!😊

**Comment by Ultrahalf** [comment]
Add duration column would be cool, right?

**Comment by vybhav72954** [comment]
@Ultrahalf As in the Duration of the Event? That is a good idea, but we do have a `timeline` for that,
