### ISSUE TITLE
The ACM MM opensource competition link gives a 404 error 

### ISSUE THREAD

**Issue by jfarhan** [deepanshu1422/List-Of-Open-Source-Internships-Programs#29]
This is the link right here https://sigmm.org/Resources/software/ossc

**Comment by deepanshu1422** [comment]
Sir, If possible.. could you please open a pull request

**Comment by saurabhhere** [comment]
Hi @deepanshu1422 , if no one is working on it I can fix this issue if you want.

**Comment by deepanshu1422** [comment]
Yeah sure, Please ho ahead!
