### ISSUE TITLE
Segregate all the open source programs month-wise in order of approaching deadline

### ISSUE THREAD

**Issue by deepanshu1422** [deepanshu1422/List-Of-Open-Source-Internships-Programs#51]

**Comment by vybhav72954** [comment]
Should we segregate by deadlines, or by the starting date of the programs?

**Comment by deepanshu1422** [comment]
@vybhav72954, In my opinion, it should be segregated by starting date of programs as the earlier the participant starts... more will be the chances of getting selected

**Comment by CmeherGit** [comment]
Tweag I/O Summer Internship is not available for 2020. I have checked this by going to their website.

**Comment by vybhav72954** [comment]
> Tweag I/O Summer Internship is not available for 2020. I have checked this by going to their website.

Can you kindly check if there Is any info for 2021, if there is none, please open a separate issue for that 😄

**Comment by CmeherGit** [comment]
Sorry for the late reply. Till now no info is provided on the website for Tweag I/O Summer Internship 2021.

**Comment by vybhav72954** [comment]
I see, Tweag for now has been removed in #65
