### ISSUE TITLE
A GitHub Action to ensure all the links are working!!!

### ISSUE THREAD

**Issue by vybhav72954** [deepanshu1422/List-Of-Open-Source-Internships-Programs#57]
@deepanshu1422 Do you think this would be a good idea?

**Comment by deepanshu1422** [comment]
Yeah , This idea is fantastic!

**Comment by adi-g15** [comment]
Found these two in case we would use available actions

https://github.com/marketplace/actions/markdown-link-check
https://github.com/marketplace/actions/lychee-link-checker-action

**Comment by vybhav72954** [comment]
@adi-g15 The problem is, we need a custom action kind of thing. Considering there are multiple non-removable errors with to `md` file. Like Long Lines, Spellings (Names of Colleges and programs), we will need our own custom set of rules, along with an action, that's what am going to start working on now though.

**Comment by vybhav72954** [comment]
Closed in #59
