### ISSUE TITLE
Some programs seem dead

### ISSUE THREAD

**Issue by Huy-Ngo** [deepanshu1422/List-Of-Open-Source-Internships-Programs#60]
By dead, I mean the program has been stopped before 2020.

- [Tweag IO](https://www.tweag.io/blog/2019-03-11-internships/): the post was from 2019
- [SOCIS](https://www.esa.int/Enabling_Support/Space_Engineering_Technology/SOCIS_The_ESA_Summer_of_Code_in_Space): the [dedicated website](https://socis.esa.int/) is not accessible
- [Tor Summer of Privacy](https://gitlab.torproject.org/legacy/trac/-/wikis/org/TorSoP): the information is from 2015
- [DataONE](https://old.dataone.org/internships): There isn't a program in 2020. Moreover, the page is marked as "old", which probably means they abandoned it.
- [OWASP](https://owasp.org/index.php/GSoC2019_Ideas): It leads to a Not Found page.
- [Segment Open Fellowship](https://open.segment.com/fellowship): The page doesn't include any information about the program.
- [ICFOSS](https://icfoss.in/event/invitation-for-interns-0): It seemingly stopped after 2017
- [ERPNext](https://erpnext.org/esoc): Seems stopped after 2018
- [John Hunter Matplotlib Summer Fellowship](https://numfocus.org/programs/john-hunter-technology-fellowship): same as above

I think they can be grouped as "Programs that are not recently active".

**Comment by vybhav72954** [comment]
Thank you for the information. If you want i can assign you this issue.

Else i will sort these from my end.

**Comment by vybhav72954** [comment]
Assigning it to myself.

**Comment by vybhav72954** [comment]
TODO:
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
