### ISSUE TITLE
GirlScript Summer of Code 2021 updated link

### ISSUE THREAD

**Issue by Shanu1515** [deepanshu1422/List-Of-Open-Source-Internships-Programs#61]
This is the link: https://gssoc.girlscript.tech/

**Comment by vybhav72954** [comment]
Do you want to open a PR, or shall I do it from my side 😄

**Comment by Shanu1515** [comment]
Ok I'll open the PR😅

**Comment by vybhav72954** [comment]
It's up to you... We generally encourage people, cause this repo is dedicated to open source after all, if you want you can open one!!! But in the case for some reason, you are unable to, I would do it from my side 👍🏻

**Comment by Shanu1515** [comment]
I have opened PR

**Comment by vybhav72954** [comment]
Thank you
