### ISSUE TITLE
We should also add the start date and end date of program....

### ISSUE THREAD

**Issue by gaurav24072002** [deepanshu1422/List-Of-Open-Source-Internships-Programs#63]
Hey!!!
We should also add the starting period and ending period of the open-source-program to make it more informatic and easy....
What do you Think??

**Comment by gaurav24072002** [comment]
Like we should add two more column with start date and end date.....
example-GSOC- start date(March 29, 2021) and end date(April 13, 2021)

**Comment by vybhav72954** [comment]
@gaurav24072002 Great idea.

In conjunction with #51 

In case you want to take this, I can assign this to you

**Comment by gaurav24072002** [comment]
Yes, sure Please....
I would be very happy to contribute on it and also can I add more such open source program like outreachy etc...
Please assign it to me!!

**Comment by vybhav72954** [comment]
In case you need any help, feel free to comment here. We can take the discussion to Discords as well 😄

**Comment by vybhav72954** [comment]
Hey @gaurav24072002 How are you, Any updates?

**Comment by gaurav24072002** [comment]
I have made a pull request for it see it on #70
