### ISSUE TITLE
Remove Dead Links as observed in the MarkDown Action.

### ISSUE THREAD

**Issue by vybhav72954** [deepanshu1422/List-Of-Open-Source-Internships-Programs#69]
We recently implemented a MarkDOwn Link checking action for this List.

The Link checker found various dead links. The report can be found [here](https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs/actions/runs/605842690)

These links should be removed but they should be checked once again for ensuring that the action is not doing any mistake.

**Comment by chiragbansal-45** [comment]
I would like to take this issue.

**Comment by chiragbansal-45** [comment]
do you want me to check all the links or the dead link only?

**Comment by vybhav72954** [comment]
@chiragbansal-45 The dead links can be found [here already](https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs/actions/workflows/md_link.yml)

I want you to check, if the domains have shifted to somewhere else, there is a typo, or are the programs are completely dead.

After that please comment here, and then you can open a PR regarding the same

**Comment by chiragbansal-45** [comment]
okay! got it

**Comment by chiragbansal-45** [comment]
I have checked and did the necessary edits. but in doing so I have committed many times because of some error. so, what should I do now?

**Comment by vybhav72954** [comment]
Sorry i didn't get it.

In case you want to start fresh.

Rebase master, and make a new branch.

**Comment by vybhav72954** [comment]
> I have checked and did the necessary edits. but in doing so I have committed many times because of some error. so, what should I do now?

I will have a look at your fork if I can figure out whats going on.

**Comment by chiragbansal-45** [comment]
okay!

**Comment by chiragbansal-45** [comment]
> > I have checked and did the necessary edits. but in doing so I have committed many times because of some error. so, what should I do now?
> 
> I will have a look at your fork if I can figure out whats going on.

yes, please

**Comment by vybhav72954** [comment]
> > > I have checked and did the necessary edits. but in doing so I have committed many times because of some error. so, what should I do now?
> > 
> > 
> > I will have a look at your fork if I can figure out whats going on.
> 
> yes, please

A piece of advice for you. Generally, it's not recommended to make commits in the `master` or `main` branch of your fork.

You should make a new branch from the master using `git checkout -b <name of new branch>` (without the chevrons of course).
(`-b` is for making a new branch)
Then do your changes, do a `git add` and then `git commit` 

Then push your changes using `git push -u origin <name of new branch>`

By following this workflow, you will notice that if in any case, you mess up something, you can again check out back to master using `git checkout master` and make a new branch.

In your case, we can do 2 things:

Either we Rebase the master branch (professional method).

Or we can make a new fork (It's a workaround, but is far easier).

If you know how to rebase, or you want to rebase, I can help you with that, or else you can delete the fork, and make a new PR.

**Comment by vybhav72954** [comment]
Or maybe you aren't using Comand Line Interface, is that true?

**Comment by chiragbansal-45** [comment]
> Or maybe you aren't using Comand Line Interface, is that true?

yes, I was not using CLI as I thought it can be done easily directly.
 I think I should rebase the master branch and then create a new branch. 
also, thank you for helping.

**Comment by chiragbansal-45** [comment]
I tried to rebase by `git rebase -i HEAD~10` , but it didn't work can you help me with doing rebase.

**Comment by vybhav72954** [comment]
You will have to set up an upstream using command.

```git remote add upstream https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs.git```

The rebase your master with upstream.
Alternatively ```git pull --rebase upstream``` or ```git pull``` can provide the same result depending upon the working tree.

I would still recommend deleting your fork and making a new one though.

Adding an upstream is necessary because you have diverged ```origin/master``` with your 10 commits

**Comment by chiragbansal-45** [comment]
okay, I will make a new fork then.

**Comment by chiragbansal-45** [comment]
I did all the changes in a new branch. should I create a PR now?

**Comment by vybhav72954** [comment]
> I did all the changes in a new branch. should I create a PR now?

Yes, please. Eagerly waiting
