### ISSUE TITLE
Add important README badges. 

### ISSUE THREAD

**Issue by vybhav72954** [deepanshu1422/List-Of-Open-Source-Internships-Programs#71]
There are multiple Repos like [shields](https://github.com/badges/shields), [badges](https://github.com/dwyl/repo-badges) and many [more](https://github.com/dwyl/repo-badges).

As this Repo is a markdown file, some badges will increase the readability of the Repo. 

Contributors before opening a PR, should comment down here that what badges should be added in the Repo.

**Comment by PawelBorkar** [comment]
@vybhav72954 I think we should make it more eye-catching by adding a header to it and badges such as opensource open-source-internship programs oss-community
We can also add CONTRIBUTING.md and License files to the README.md

**Comment by vybhav72954** [comment]
Let's not add CONTRIBUTING.md or README.md as of now.

You can add the badges, I can assign this one to you!!!

**Comment by PawelBorkar** [comment]
@vybhav72954 Sure!
Please go ahead.

**Comment by PawelBorkar** [comment]
It would be nice if we make little bit of changes in the README as well to make it more appealing to the new visitors.

**Comment by vybhav72954** [comment]
Feel free to do the same.

**Comment by PawelBorkar** [comment]
Hi @vybhav72954 ,
I think we should add a _validate link passing badge_ as we are having workflow regarding the validation of the links in the README and if we add a LICENSE to the project then we have to include the badge for the same as well. We can also add a badge that indicates contributions are welcome.

Let me know if you have any suggestions.

**Comment by deepanshu1422** [comment]
@pawelborkar  Great suggestion buddy 
@vybhav72954  I think we should go ahead with this approach.

@pawelborkar  Please feel free to contribute 🤝
