### ISSUE TITLE
Make this an awesome list?

### ISSUE THREAD

**Issue by harsh183** [deepanshu1422/List-Of-Open-Source-Internships-Programs#74]
I feel like this really has the vibe for it and might get it discovered by more people.

**Comment by vybhav72954** [comment]
Can you elaborate what you actually mean by Awesome List.

**Comment by harsh183** [comment]
https://github.com/sindresorhus/awesome - include it here and add a badge on top of the repo

**Comment by vybhav72954** [comment]
That's a great idea. Thank you so much!!!
