### ISSUE TITLE
Hyperledger Internship Program link is broken 

### ISSUE THREAD

**Issue by coderjojo** [deepanshu1422/List-Of-Open-Source-Internships-Programs#9]
[Hyperledger Internship Program](https://wiki.hyperledger.org/display/INTERN/Hyperledger+Internship+Program#HyperledgerInternshipProgram-2019ProgramTimeline) link is not working anymore.

I guess they have transferred it to [Hyperledger Confluence](https://wiki.hyperledger.org/display/INTERN/How+to+Apply).

**Comment by deepanshu1422** [comment]
Updated the changes, Thanks for pointing out!
