### ISSUE TITLE
Suggestion about Open source internship restrictions

### ISSUE THREAD

**Issue by yokwejuste** [deepanshu1422/List-Of-Open-Source-Internships-Programs#96]
Why going through some internships, I realized they were having some sort of geographical restrictions. My suggestion is, can we not add a column for the precision of these areas? :)

**Comment by deepanshu1422** [comment]
Sure, buddy, we can!

Can you help us achieve that ?

**Comment by yokwejuste** [comment]
Yeah of course, when I'm done I make a pull request.
