### ISSUE TITLE
UNDP Geospatial Data Science Internship - Deadline 7 March 2022 

### ISSUE THREAD

**Issue by Swetha-Kolluri** [deepanshu1422/List-Of-Open-Source-Internships-Programs#99]
Can you please circulate UNDP Internship opportunity advertised below:

https://jobs.undp.org/cj_view_job.cfm?cur_job_id=105057

https://www.linkedin.com/posts/undp-in-india_hiringnow-applynow-vacancy-activity-6904667750678294528-g5NQ

**Comment by rakshith6404** [comment]
I am looking forward for this could u tell me in brief ?
